### ISSUE TITLE
[question] Types for @dark 

### ISSUE THREAD

**Issue by RubyHuntsman** [danpacho/tailwindest#94]
Hey 👋 
I struggling with types. How use types with `@dark` color? It's an icon component so I use text colors like `text-white` for example
  ``` typescript
  export type IconProps = {
    color?: Tailwindest['color'];
    darkColor?: Tailwindest['@dark???']; // <==
    ...
  }
```

**Comment by danpacho** [comment]
## Problem statements

Unfortunately nested type should be calculated, `typescript` can't statically infer the exact type definition **before we define real object**. 

That's why we can't get exact type definition for deeply nested className like
`dark:bg-red-50, dark:hover:bg-red-50, dark:hover:active:bg-red-50 ...`.

```ts
export type IconProps = {
  color?: Tailwindest['color'];    // <-- "text-red-50" | "text-red-100" | ...
  
  // ❌ These will be <any>, because ts can't infer static type for this condition
  darkColor?: Tailwindest['@dark']['color']; // <-- any
  darkHoverColor?: Tailwindest['@dark'][':hover']['color']; // <-- any
  ...
}
```

But fortunately, there are two solutions for this problem.

## Solution 1: Define it manually

First method is quite simple and straightforward(but quite annoying...).

Add nest condition by manually using `ts` literal feature.

```ts
import {type Tailwindest} from "tailwindest";

type Tw = Required<Tailwindest>;

type BgDark = `dark:${Tw["backgroundColor"]}`;
type BgDarkHover = `dark:hover:${Tw["backgroundColor"]}`;

const bg1: BgDark = "dark:bg-red-100";
const bg2: BgDarkHover = "dark:hover:bg-red-100";
```

But as you can it is not ideal solution. For this kind of repeated process, we should define some util type for it.

## Solution 2: Define utility type

Here is example solution to define nest condition className.

```ts
type ExtractKeys<
    Key,
    Pattern extends string,
> = Key extends `${Pattern}${infer Rest}` ? Exclude<Rest, Pattern> : never

type Keys = ExtractKeys<keyof Tw, "@" | "::">
type WithStringLiteral = string & {}

export type Nest<
    Prefix extends Keys | WithStringLiteral,
    ClassName extends string,
> = ClassName extends undefined | never ? never : `${Prefix}:${ClassName}`
```

Usage

```ts
import { type Tailwindest } from "tailwindest";
import { type Nest } from "~/util/tw"

type Tw = Required<
    Tailwindest<{
        color: "gra-100"
    }>
>

type Dark = Nest<"dark", Tw["color"]>
type DarkHover = Nest<"dark:hover", Tw["color"]>
```
1. `Dark` example result
    <img width="678" alt="스크린샷 2024-04-01 오후 9 40 02" src="https://github.com/danpacho/tailwindest/assets/53421296/86bca457-8fae-443d-bdda-411749fdb55b">
2. `DarkHover` example result
    <img width="678" alt="스크린샷 2024-04-01 오후 9 40 41" src="https://github.com/danpacho/tailwindest/assets/53421296/f5db993b-5ec8-4bff-8070-67155bbff35a">

> **Information 🔮**
> 
> If you prefer this kind of solution, then let me know :) It will be included in lib.

**Comment by RubyHuntsman** [comment]
Firstly, I would like to appreciate your determination in the development of this lib and your responsiveness in responses. I appreciate it very much 😄 

The first solution is very poor, and you are right. The second one is probably appropriate. At first, I thought it would be great to go a step further and export types with nice names. Like for example

``` typescript
// Types exported from lib
export type TailwindestDark<T> = Nest<'dark', Tw[T]>;
export type TailwindestDarkHover<T> = Nest<'dark:hover', Tw[T]>;

type MyTypedDarkColors = TailwindestDark<'color'>;
type MyTypedDarkHoverColors = TailwindestDarkHover<'color'>;
```
<img width="500" alt="Screenshot 2024-04-01 at 16 55 24" src="https://github.com/danpacho/tailwindest/assets/24682602/db84ee61-68d3-4c29-94a6-b569c0ca5aa6">

But.. after seeing how many pseudo-classes there are, it's probably not possible 🤯 
The first parameter of the `Nest` type is not typed. I don't know if that was the intention or if it's possible. I just wanted to mention 😅 
In any case, I would support adding your solution to this lib 🔮 Tailwindest takes types in component writing to a completely different level ⛰️
